// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
// [[Rcpp::depends(dlib)]]
// [[Rcpp::plugins(cpp11)]]

using namespace Rcpp;

// kmap
Rcpp::List kmap(const arma::mat& x, const arma::cube& y, const arma::urowvec& seeds, const unsigned int& n_clust, const unsigned int& maximum_number_of_iterations, const unsigned int& number_of_threads, const unsigned int& parallel_method, const double& shift_upper_bound, const double& dilation_upper_bound, const double& tolerance, const bool& use_fence, const bool& check_total_similarity, const bool& use_verbose, const bool& compute_original_centers, const std::string& interpolation_method, const std::string& warping_method, const std::string& center_method, const std::string& dissimilarity_method, const std::string& optimizer_method);
RcppExport SEXP _fdakmapp_kmap(SEXP xSEXP, SEXP ySEXP, SEXP seedsSEXP, SEXP n_clustSEXP, SEXP maximum_number_of_iterationsSEXP, SEXP number_of_threadsSEXP, SEXP parallel_methodSEXP, SEXP shift_upper_boundSEXP, SEXP dilation_upper_boundSEXP, SEXP toleranceSEXP, SEXP use_fenceSEXP, SEXP check_total_similaritySEXP, SEXP use_verboseSEXP, SEXP compute_original_centersSEXP, SEXP interpolation_methodSEXP, SEXP warping_methodSEXP, SEXP center_methodSEXP, SEXP dissimilarity_methodSEXP, SEXP optimizer_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::urowvec& >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type n_clust(n_clustSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type maximum_number_of_iterations(maximum_number_of_iterationsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type number_of_threads(number_of_threadsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type parallel_method(parallel_methodSEXP);
    Rcpp::traits::input_parameter< const double& >::type shift_upper_bound(shift_upper_boundSEXP);
    Rcpp::traits::input_parameter< const double& >::type dilation_upper_bound(dilation_upper_boundSEXP);
    Rcpp::traits::input_parameter< const double& >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const bool& >::type use_fence(use_fenceSEXP);
    Rcpp::traits::input_parameter< const bool& >::type check_total_similarity(check_total_similaritySEXP);
    Rcpp::traits::input_parameter< const bool& >::type use_verbose(use_verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type compute_original_centers(compute_original_centersSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type interpolation_method(interpolation_methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type warping_method(warping_methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type center_method(center_methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dissimilarity_method(dissimilarity_methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type optimizer_method(optimizer_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(kmap(x, y, seeds, n_clust, maximum_number_of_iterations, number_of_threads, parallel_method, shift_upper_bound, dilation_upper_bound, tolerance, use_fence, check_total_similarity, use_verbose, compute_original_centers, interpolation_method, warping_method, center_method, dissimilarity_method, optimizer_method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fdakmapp_kmap", (DL_FUNC) &_fdakmapp_kmap, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdakmapp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
