# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kmap <- function(x, y, seeds, warping_options, n_clust, maximum_number_of_iterations, number_of_threads, parallel_method, distance_relative_tolerance, use_fence, check_total_similarity, use_verbose, compute_overall_center, interpolation_method, warping_method, center_method, dissimilarity_method, optimizer_method) {
    .Call('_fdakmapp_kmap', PACKAGE = 'fdakmapp', x, y, seeds, warping_options, n_clust, maximum_number_of_iterations, number_of_threads, parallel_method, distance_relative_tolerance, use_fence, check_total_similarity, use_verbose, compute_overall_center, interpolation_method, warping_method, center_method, dissimilarity_method, optimizer_method)
}

